/*
 *    EDGEINTS.H
 */
/*
#define LOW 		1
#define CHANGE 		2
#define RISING 		4
#define FALLING 	8
#define RISING_EDGE  0x4
#define FALLING_EDGE 0x8
#define BOTH_EDGES   0xc
// Output compare.
#define TOGGLE  	0x14
#define CLEAR	 	0x8
#define SET   		0x1c
typedef void(*PFNCALLBACK)(void);
void InitEdgeInterrupt();
void attachInterrupt( int which, PFNCALLBACK cb, int mode);
void detachInterrupt(int which);
void interruptMode(int which, int mode );
void SetTime(int which, int counts );
void noInterrupts();
void interrupts(void);
*/
